import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { galleryApi } from '../api/client';
import type { GeneratedImage } from '../api/client';
import './Gallery.css';

const PURPOSES = ['all', 'autonomous', 'article', 'relational', 'dream'] as const;
const STYLES = ['all', 'painterly', 'sketch', 'photorealistic', 'abstract', 'watercolor', 'digital_art', 'dreamlike'] as const;

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function formatPurpose(purpose: string): string {
  return purpose.charAt(0).toUpperCase() + purpose.slice(1);
}

function formatStyle(style: string | null): string {
  if (!style) return 'Unknown';
  return style.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

export function Gallery() {
  const [selectedPurpose, setSelectedPurpose] = useState<string>('all');
  const [selectedStyle, setSelectedStyle] = useState<string>('all');
  const [selectedImage, setSelectedImage] = useState<GeneratedImage | null>(null);
  const [page, setPage] = useState(0);
  const pageSize = 24;

  const { data, isLoading, error } = useQuery({
    queryKey: ['gallery', selectedPurpose, selectedStyle, page],
    queryFn: () => galleryApi.list({
      purpose: selectedPurpose === 'all' ? undefined : selectedPurpose,
      style: selectedStyle === 'all' ? undefined : selectedStyle,
      limit: pageSize,
      offset: page * pageSize,
    }).then(r => r.data),
  });

  const totalPages = data ? Math.ceil(data.total / pageSize) : 0;

  const getImageUrl = (image: GeneratedImage) => {
    return galleryApi.getUrl(image);
  };

  return (
    <div className="gallery-page">
      <header className="page-header">
        <div className="header-content">
          <h1>Gallery</h1>
          <p className="subtitle">Images generated by Cass</p>
        </div>
        {data && (
          <div className="image-count">
            {data.total} image{data.total !== 1 ? 's' : ''}
          </div>
        )}
      </header>

      {/* Filters */}
      <div className="gallery-filters">
        <div className="filter-group">
          <label>Purpose</label>
          <div className="filter-buttons">
            {PURPOSES.map(purpose => (
              <button
                key={purpose}
                className={`filter-btn ${selectedPurpose === purpose ? 'active' : ''}`}
                onClick={() => { setSelectedPurpose(purpose); setPage(0); }}
              >
                {purpose === 'all' ? 'All' : formatPurpose(purpose)}
              </button>
            ))}
          </div>
        </div>

        <div className="filter-group">
          <label>Style</label>
          <div className="filter-buttons">
            {STYLES.map(style => (
              <button
                key={style}
                className={`filter-btn ${selectedStyle === style ? 'active' : ''}`}
                onClick={() => { setSelectedStyle(style); setPage(0); }}
              >
                {style === 'all' ? 'All' : formatStyle(style)}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Loading / Error states */}
      {isLoading && (
        <div className="gallery-loading">Loading images...</div>
      )}

      {error && (
        <div className="gallery-error">Failed to load images</div>
      )}

      {/* Gallery Grid */}
      {data && data.images.length > 0 && (
        <>
          <div className="gallery-grid">
            {data.images.map(image => {
              const url = getImageUrl(image);
              return (
                <div
                  key={image.id}
                  className="gallery-item"
                  onClick={() => setSelectedImage(image)}
                >
                  {url ? (
                    <img src={url} alt={image.prompt} loading="lazy" />
                  ) : (
                    <div className="no-image">No preview</div>
                  )}
                  <div className="gallery-item-overlay">
                    <span className={`purpose-badge ${image.purpose}`}>
                      {formatPurpose(image.purpose)}
                    </span>
                    {image.style && (
                      <span className="style-badge">
                        {formatStyle(image.style)}
                      </span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          {/* Pagination */}
          {totalPages > 1 && (
            <div className="gallery-pagination">
              <button
                className="page-btn"
                disabled={page === 0}
                onClick={() => setPage(p => Math.max(0, p - 1))}
              >
                ← Previous
              </button>
              <span className="page-info">
                Page {page + 1} of {totalPages}
              </span>
              <button
                className="page-btn"
                disabled={page >= totalPages - 1}
                onClick={() => setPage(p => p + 1)}
              >
                Next →
              </button>
            </div>
          )}
        </>
      )}

      {/* Empty state */}
      {data && data.images.length === 0 && (
        <div className="gallery-empty">
          <p>No images found</p>
          {(selectedPurpose !== 'all' || selectedStyle !== 'all') && (
            <p className="empty-hint">Try adjusting your filters</p>
          )}
        </div>
      )}

      {/* Lightbox Modal */}
      {selectedImage && (
        <div className="lightbox" onClick={() => setSelectedImage(null)}>
          <div className="lightbox-content" onClick={e => e.stopPropagation()}>
            <button className="lightbox-close" onClick={() => setSelectedImage(null)}>
              ×
            </button>

            <div className="lightbox-image">
              {getImageUrl(selectedImage) ? (
                <img src={getImageUrl(selectedImage)!} alt={selectedImage.prompt} />
              ) : (
                <div className="no-image large">No preview available</div>
              )}
            </div>

            <div className="lightbox-info">
              <div className="lightbox-meta">
                <span className={`purpose-badge ${selectedImage.purpose}`}>
                  {formatPurpose(selectedImage.purpose)}
                </span>
                {selectedImage.style && (
                  <span className="style-badge">
                    {formatStyle(selectedImage.style)}
                  </span>
                )}
                <span className="date">
                  {formatDate(selectedImage.created_at)}
                </span>
              </div>

              <div className="lightbox-prompt">
                <label>Prompt</label>
                <p>{selectedImage.prompt}</p>
              </div>

              {selectedImage.width && selectedImage.height && (
                <div className="lightbox-dimensions">
                  {selectedImage.width} × {selectedImage.height}
                  {selectedImage.generation_time_ms && (
                    <span className="gen-time">
                      • Generated in {(selectedImage.generation_time_ms / 1000).toFixed(1)}s
                    </span>
                  )}
                </div>
              )}

              {selectedImage.context_id && (
                <div className="lightbox-context">
                  <label>Context</label>
                  <p className="context-id">{selectedImage.context_id}</p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
